name: Node.js CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ./lab-2-improvedode && npm install
    - run: cd ./lab-2-improvedode && npm lint
    - run: cd ./lab-2-improvedode && npm test:coverage
      env:
        CI: true